version: '3.3'

services:
  db:
    image: mysql:8.0
    container_name: soccer_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: soccer_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - soccer-network

volumes:
  db_data:

networks:
  soccer-network: